Exit unknown if `bundle-audit update` fails
Because:

* `bundle-audit update` downloads a copy of the ruby-advisory-db inside
  the user's home directory. This can cause issues if the user running
  the script does not have a writable home directory.
* If the db fails to update this can result in false positives.

This change:

* Check if the update command fails, exit unknown if it does.
* Adds a test for this case.

diff --git a/check_bundle_audit b/check_bundle_audit
--- a/check_bundle_audit
+++ b/check_bundle_audit
@@ -111,7 +111,10 @@ if [ ! -f "${PROJECT_PATH}/Gemfile.lock" ]; then
 fi
 
 # update the ruby advisory db
-$BUNDLE_AUDIT_PATH update >/dev/null 2>&1
+if ! $BUNDLE_AUDIT_PATH update >/dev/null 2>&1; then
+  echo "UNKNOWN: Unable to update ruby-advisory-db"
+  exit $UNKNOWN
+fi
 
 # run bundle-audit
 REPORT=$(cd $PROJECT_PATH; $BUNDLE_AUDIT_PATH)
